version: "3.8"
services:
    php:
        container_name: lakubo-php-fpm
        build:
            context: .
            target: php
            args:
                - APP_NAME=${APP_NAME}
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www/${APP_NAME}
        volumes:
            - ./:/var/www/${APP_NAME}
        ports:
            - 8000:8000
