version: "3.9"
services:
    php:
        container_name: lakubo-app
        build:
            context: .
            target: php
            args:
            - APP_NAME=${APP_NAME}
            - APP_ENV=${APP_ENV}
        environment:
            - APP_NAME=${APP_NAME}
            - APP_ENV=${APP_ENV}
            - APP_KEY=${APP_KEY}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_HOST=${DB_HOST}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        working_dir: /var/www/${APP_NAME}
        volumes:
            - ./:/var/www/${APP_NAME}
        ports:
            - "8001:8000"
        networks:
            - env-server
networks:
    env-server:
        name: ${NETWORK_NAME}
        driver: bridge
