version: "3.9"
services:
    app:
        container_name: lakubo2
        env_file:
            - .env
        restart: always
        build:
            context: .
            target: php
            args:
                - APP_NAME=${APP_NAME}
                - APP_ENV=${APP_ENV}
        working_dir: /var/www/${APP_NAME}
        volumes:
            - ./:/var/www/${APP_NAME}
        ports:
            - '8003:80'
        networks:
            - env-server
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8003" ]
            interval: 30s
            timeout: 10s
            retries: 3
networks:
    env-server:
        name: ${NETWORK_NAME}
        driver: bridge
