# fly.toml app configuration file generated for lakubo on 2024-06-19T21:41:15+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lakubo'
primary_region = 'sin'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
APP_NAME = "Lakubo"
APP_ENV = "production"
APP_DEBUG = "false"
DB_CONNECTION = "mysql"
RAJAONGKIR_API_URL = "https://api.rajaongkir.com/starter"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "info"
LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
BROADCAST_DRIVER = "log"
CACHE_DRIVER = "file"
FILESYSTEM_DISK = "local"
QUEUE_CONNECTION = "sync"
SESSION_DRIVER = "cookie"
SESSION_SECURE_COOKIE = "true"
OPCACHE_ENABLE = "1"
OPCACHE_ENABLE_CLI = "1"
OPCACHE_VALIDATE_TIMESTAMPS = "1"
OPCACHE_REVALIDATE_FREQ = "30"
MIDTRANS_IS_PRODUCTION = "false"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[mounts]]
source = 'lakubo_storage'
destination = '/var/www/html/storage'
