# fly.toml app configuration file generated for lakubo-app on 2024-06-27T06:09:21+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lakubo-app'
primary_region = 'sin'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
  APP_DEBUG = 'false'
  APP_ENV = 'production'
  APP_NAME = 'Lakubo'
  BROADCAST_DRIVER = 'log'
  CACHE_DRIVER = 'file'
  DB_CONNECTION = 'mysql'
  FILESYSTEM_DISK = 'local'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  OPCACHE_ENABLE = '1'
  OPCACHE_ENABLE_CLI = '0'
  OPCACHE_REVALIDATE_FREQ = '30'
  OPCACHE_VALIDATE_TIMESTAMPS = '1'
  QUEUE_CONNECTION = 'sync'
  RAJAONGKIR_API_URL = 'https://api.rajaongkir.com/starter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[[mounts]]
  source = 'lakubo_storage'
  destination = '/var/www/html/storage'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
