<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Spatie\Permission\Exceptions\UnauthorizedException;
use Throwable;

class Handler extends ExceptionHandler
{

    protected $levels = [
        //
    ];

    protected $dontReport = [
        //
    ];

    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    public function register()
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    protected function unauthenticated($request, AuthenticationException|\Illuminate\Auth\AuthenticationException $exception)
    {
        if ($request->expectsJson()) {
            return response()->json(['error' => 'Silahkan Login terlebih dahulu.'], 401);
        }

        return redirect()->guest('login');
    }

    /*public function render($request, Throwable $e)
    {
        if ($e instanceof UnauthorizedException) {
            return response()->view("errors.403", [
                "exception" => $e
            ], 403);
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }*/
}
